### ISSUE TITLE
Feature | Implement standard CI/CD (GitOps oriented) workflow to manage ECS deployments

### ISSUE THREAD

**Issue by angelofenoglio** [binbashar/le-tf-infra-aws#580]
## Describe the Feature

- Review and implement a standard CI/CD (GitOps oriented) workflow utilizing Github Actions to deploy, modify and manage ECS services.
  - Ref design: https://binbashar.slack.com/archives/C07CAGK5P8E/p1737729891245619 

## Expected Behavior

Once implemented, the Reference Architecture should support GitOps using GitHub Actions for ECS services. This would allow for more streamlined and automated deployment workflows.

**Comment by exequielrafaela** [comment]
Simplify approach for the ECS ref arch layer with the new blue/green native deployment feature. Check ref links below:
- https://aws.amazon.com/blogs/aws/accelerate-safe-software-releases-with-new-built-in-blue-green-deployments-in-amazon-ecs/
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-blue-green.html

**Comment by lgallard** [comment]
@exequielrafaela @diego-ojeda-binbash @angelofenoglio  to tackle this issue @hecberco and I discussed and designed the following proposal.  

@hecberco stumbled upon this issue: 

>  Current implementation of the layers couples infrastructure with application deployments, as changes to the container image are defined in the task definition, and this resource is defined inside the cluster. This means that this layers requires that app source code is developed in one repo where container image is created and pushed, and then update the container image tags in this repo to perform the deployment.

The solution takes this into consideration and the main goal, which is to implement a GitOps workflow for ECS. Without further ado, this is the proposal:

--- 

# ECS GitOps CI/CD Workflow Analysis - Issues #580 & #933

## 🎯 Executive Summary

*This analysis addresses the critical need to modernize ECS deployments within the Binbash Leverage Reference Architecture, moving from manual infrastructure operations to true GitOps automation while maintaining enterprise-grade security and operational excellence.*

**GitHub Issues**: 
- [#580 - Feature | Implement standard CI/CD (GitOps oriented) workflow to manage ECS deployments](https://github.com/binbashar/le-tf-infra-aws/issues/580)
- [#933 - Spike: Investigate current implementation](https://github.com/binbashar/le-tf-infra-aws/issues/933)

**Goal**: Implement a GitOps-oriented CI/CD workflow using GitHub Actions for ECS deployments with blue-green deployment capabilities, using **Leverage CLI exclusively** for all infrastructure operations. This solution will enable development teams to deploy applications without requiring infrastructure expertise while maintaining security, compliance, and operational consistency.

**Key Findings**: 
- ✅ AWS native blue-green deployment is supported via Binbash ECS module
- ❌ Current architecture couples infrastructure with application deployments  
- 🔧 Full automation possible using repository dispatch + Leverage CLI approach
- ✅ **Refined Solution**: Parameterized GitOps with automatic validation

---

## 📊 Current Architecture Analysis

*The current deployment process requires developers to modify infrastructure code for every application update, creating bottlenecks and violating separation of concerns principles. This analysis reveals why the existing approach doesn't scale for modern development teams.*

### Current Deployment Flow (Problematic)

```mermaid
graph TD
    A[Developer] --> B[Terraform Code Change]
    B --> C[Update locals.tf with new image version]
    C --> D[leverage tf plan]
    D --> E[leverage tf apply]
    E --> F[ECS Service Update]
    F --> G[Rolling Deployment]
    G --> H[Service Updated]
    
    style A fill:#e1f5fe
    style B fill:#fff3e0
    style C fill:#ffebee
    style F fill:#f3e5f5
    style H fill:#e8f5e8
```

### Current Implementation Files

| Component | File | Lines | Purpose |
|-----------|------|-------|---------|
| **ECS Cluster** | [`apps-devstg/us-east-1/ecs-demoapps/ecs.tf`](https://github.com/binbashar/le-tf-infra-aws/blob/master/apps-devstg/us-east-1/ecs-demoapps/ecs.tf#L23-L124) | 23-124 | Main ECS cluster and services configuration |
| **Service Definitions** | [`apps-devstg/us-east-1/ecs-demoapps/locals.tf`](https://github.com/binbashar/le-tf-infra-aws/blob/master/apps-devstg/us-east-1/ecs-demoapps/locals.tf#L7-L89) | 7-89 | Service and container definitions with **hardcoded image versions** |
| **Load Balancer** | [`apps-devstg/us-east-1/ecs-demoapps/alb.tf`](https://github.com/binbashar/le-tf-infra-aws/blob/master/apps-devstg/us-east-1/ecs-demoapps/alb.tf#L47-L131) | 47-131 | ALB configuration with target groups |

### Current Module Architecture

**Terraform Module Used**: 
- [`binbashar/terraform-aws-ecs.git?ref=v5.12.1`](https://github.com/binbashar/terraform-aws-ecs/tree/v5.12.1)
- **Blue-Green Support**: ✅ Available via [`deployment_controller`](https://github.com/binbashar/terraform-aws-ecs/blob/master/modules/service/main.tf#L81) configuration

---

## ⚠️ Problem Statement

*The fundamental issue preventing true GitOps adoption is the architectural coupling between application deployments and infrastructure changes. This coupling creates operational friction, slows development velocity, and prevents teams from implementing modern CI/CD practices.*

### Critical Coupling Issue

The current implementation has a **tight coupling** between infrastructure and application deployments:

```hcl
# From locals.tf:14-15 - PROBLEMATIC HARDCODING
web = {
  image   = "docker.l5d.io/buoyantio/emojivoto-web"
  version = "v11"  # ❌ This requires Terraform changes for app updates!
```

### Impact on GitOps

❌ **Current Problems**:
- Application updates require infrastructure changes
- No separation between app development and infrastructure management
- Cannot implement true CI/CD for applications
- Manual Terraform operations for every deployment

---

## 🔄 AWS Blue-Green Deployment Capabilities

*Blue-green deployments provide zero-downtime application updates by maintaining two identical production environments and switching traffic between them. AWS ECS now offers native support for this deployment strategy, eliminating the need for custom orchestration while providing enterprise-grade safety mechanisms.*

### Native AWS ECS Blue-Green Support

**AWS Documentation**: [ECS Blue/Green Deployments](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-blue-green.html)

**Key Features**:
- ✅ Zero downtime deployments
- ✅ Automatic rollback capabilities
- ✅ Traffic shifting with validation
- ✅ Lifecycle hooks for automated testing

**Technical Requirements**:
- Additional target group in ALB for traffic switching
- Deployment controller type set to blue-green
- Health check configuration
- Bake time configuration

---

## 🎯 Proposed Solution Architecture

*This solution implements true GitOps principles by completely separating application and infrastructure concerns. The repository dispatch pattern enables cross-repository automation while the Leverage CLI ensures all infrastructure operations maintain consistency with existing operational patterns and security requirements.*

### Full GitOps Workflow with Leverage CLI

```mermaid
graph TD
    A[Developer Merges PR] --> B[App Repository GitHub Actions]
    B --> C[Build Container Image]
    C --> D[Push to ECR with $GITHUB_SHA tag]
    D --> E[Update Parameter Store<br/>/ecs/$ENV/$SERVICE/image-tag]
    E --> F[Repository Dispatch to Infrastructure Repo]
    F --> G[Infrastructure Repository GitHub Actions]
    G --> H[Setup Leverage CLI in Runner]
    H --> I[Validate Parameter Store Updated]
    I --> J[leverage tf plan -out=tfplan]
    J --> K{Plan Validation}
    K -->|Only ECS Changes| L[leverage tf apply tfplan]
    K -->|Unexpected Changes| M[❌ Fail & Alert]
    L --> N[Binbash ECS Module Handles Deployment]
    N --> O{Blue-Green Enabled?}
    O -->|Yes| P[Blue-Green Deployment]
    O -->|No| Q[Rolling Update]
    P --> R[🚀 Deployment Complete]
    Q --> R
    
    style A fill:#e1f5fe
    style B fill:#fff3e0
    style F fill:#f3e5f5
    style G fill:#fff3e0
    style K fill:#fff9c4
    style L fill:#e8f5e8
    style M fill:#ffebee
    style R fill:#e8f5e8
```

### Deployment Sequence Flow with Leverage CLI

```mermaid
sequenceDiagram
    participant Dev as Developer
    participant App as App Repository
    participant ECR as Amazon ECR
    participant PS as Parameter Store
    participant Infra as Infrastructure Repository
    participant Leverage as Leverage CLI
    participant ECS as Binbash ECS Module
    participant AWS as AWS ECS Service
    
    Dev->>App: Merge PR to main
    App->>App: Build container image
    App->>ECR: Push image:$GITHUB_SHA
    App->>PS: Update /ecs/$ENV/$SERVICE/image-tag
    App->>Infra: Repository dispatch event
    
    Note over Infra: GitHub Actions Runner
    Infra->>Infra: Setup Leverage CLI
    Infra->>PS: Validate parameter updated
    Infra->>Leverage: leverage tf plan -out=tfplan
    Leverage->>Infra: Plan output (task definition changes)
    Infra->>Infra: Validate plan (only ECS changes)
    Infra->>Leverage: leverage tf apply tfplan
    Leverage->>ECS: Update ECS service via module
    ECS->>AWS: Create new task set (blue-green)
    AWS->>AWS: Health checks on green tasks
    AWS->>AWS: Switch traffic to green
    AWS->>AWS: Terminate blue task set
    AWS->>Infra: Deployment complete
    Infra->>Dev: Notification (success/failure)
```

### Repository Architecture Overview

*This architecture demonstrates the clear separation between application development (left) and infrastructure management (right), connected through AWS services that serve as the integration layer. The repository dispatch pattern enables cross-repository coordination while maintaining security boundaries and operational independence.*

```mermaid
flowchart TD
    subgraph AppRepo["🏗️ App Repository"]
        A1[Application Code]
        A2[Dockerfile]  
        A3[GitHub Actions Deploy]
        A4[Repository Variables<br/>• SERVICE_NAME<br/>• TARGET_ENV<br/>• ECR_REGISTRY]
    end
    
    subgraph InfraRepo["⚙️ Infrastructure Repository"]
        I1[ECS Layer Code]
        I2[Parameter Store Data Sources]
        I3[GitHub Actions ECS Deploy]
        I4[Leverage CLI Setup]
    end
    
    subgraph AWSServices["☁️ AWS Services"]
        AWS1[Amazon ECR]
        AWS2[Parameter Store]
        AWS3[ECS Service]
        AWS4[ALB Target Groups]
    end
    
    A3 -->|Build & Push| AWS1
    A3 -->|Update Parameters| AWS2
    A3 -->|Repository Dispatch| I3
    I3 -->|Setup CLI| I4
    I2 -.->|Read Parameters| AWS2
    I4 -->|Apply via Module| AWS3
    AWS3 -->|Blue-Green Deploy| AWS4
    
    style A1 fill:#e1f5fe
    style I1 fill:#fff3e0
    style AWS3 fill:#e8f5e8
```

---

## 🛠️ Technical Implementation Details

*The implementation strategy focuses on parameterization and automation while maintaining security through AWS OIDC authentication and proper secret management. These configurations enable teams to reuse the workflows across different services and environments without code duplication.*

### Repository Variables Configuration

**Application Repository Variables**:
```bash
# Repository Settings → Secrets and variables → Actions → Variables
SERVICE_NAME=emojivoto
TARGET_ENV=devstg  
ECR_REGISTRY=123456789012.dkr.ecr.us-east-1.amazonaws.com
INFRA_ORG=binbashar
INFRA_REPO=le-tf-infra-aws
INFRA_LAYER_PATH=apps-devstg/us-east-1/ecs-demoapps
```

### Application Repository Workflow

*This workflow handles the application development lifecycle: building, testing, and publishing container images, then coordinating with the infrastructure repository for deployment. It maintains complete separation from infrastructure concerns while providing full traceability.*

```yaml
name: Deploy Application
on:
  push:
    branches: [main]

env:
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}
  TARGET_ENV: ${{ vars.TARGET_ENV }}
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # For OIDC AWS authentication
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build and Push Image
        run: |
          docker build -t $ECR_REGISTRY/$SERVICE_NAME:$GITHUB_SHA \
                       -t $ECR_REGISTRY/$SERVICE_NAME:latest .
          docker push $ECR_REGISTRY/$SERVICE_NAME:$GITHUB_SHA
          docker push $ECR_REGISTRY/$SERVICE_NAME:latest
      
      - name: Update Parameter Store
        run: |
          aws ssm put-parameter \
            --name "/ecs/$TARGET_ENV/$SERVICE_NAME/image-tag" \
            --value "$GITHUB_SHA" \
            --overwrite
      
      - name: Trigger Infrastructure Deployment
        env:
          GH_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
        run: |
          gh api \
            --method POST \
            /repos/${{ vars.INFRA_ORG }}/${{ vars.INFRA_REPO }}/dispatches \
            --field event_type=deploy-ecs \
            --field client_payload='{
              "service": "'$SERVICE_NAME'",
              "image_tag": "'$GITHUB_SHA'",
              "environment": "'$TARGET_ENV'",
              "layer_path": "'${{ vars.INFRA_LAYER_PATH }}'",
              "triggered_by": "'${{ github.actor }}'",
              "app_repo": "'${{ github.repository }}'"
            }'
```

### Infrastructure Repository Workflow

*The infrastructure workflow responds to deployment requests from application repositories, validates changes through Terraform planning, and executes deployments using the Leverage CLI. This approach ensures all infrastructure operations follow established patterns while enabling automation.*

```yaml
name: ECS Deployment
on:
  repository_dispatch:
    types: [deploy-ecs]

env:
  SERVICE_NAME: ${{ github.event.client_payload.service }}
  IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
  TARGET_ENV: ${{ github.event.client_payload.environment }}
  LAYER_PATH: ${{ github.event.client_payload.layer_path }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      
      - name: Setup Leverage CLI
        run: |
          pip install leverage
          echo "PROJECT=bb" > build.env
          echo "MFA_ENABLED=false" >> build.env
          echo "TERRAFORM_IMAGE_TAG=1.9.1-tofu-0.3.0" >> build.env
      
      - name: Validate Parameters Available
        run: |
          PARAM_VALUE=$(aws ssm get-parameter \
            --name "/ecs/$TARGET_ENV/$SERVICE_NAME/image-tag" \
            --query 'Parameter.Value' --output text)
          
          if [ "$PARAM_VALUE" != "$IMAGE_TAG" ]; then
            echo "Parameter store not updated yet, waiting..."
            sleep 10
          fi
      
      - name: Plan Deployment (Validation)
        run: |
          cd $LAYER_PATH
          leverage tf plan -out=tfplan -detailed-exitcode
        id: plan
        continue-on-error: true
      
      - name: Validate Plan Output
        run: |
          if [ ${{ steps.plan.outputs.exitcode }} -eq 2 ]; then
            echo "✅ Changes detected, validating plan..."
            # Ensure only expected ECS service updates
          elif [ ${{ steps.plan.outputs.exitcode }} -eq 0 ]; then
            echo "No changes needed"
            exit 0
          else
            echo "❌ Plan failed"
            exit 1
          fi
      
      - name: Apply Deployment (Auto)
        if: steps.plan.outputs.exitcode == 2
        run: |
          cd $LAYER_PATH
          leverage tf apply tfplan
```

### Infrastructure Code Changes

*These code modifications transform the current static configuration into a dynamic system that responds to parameter changes. The use of Terraform data sources ensures that infrastructure updates are triggered only when application teams update their deployment parameters.*

```hcl
# Dynamic parameter data sources
data "aws_ssm_parameter" "image_tags" {
  for_each = {
    for service_name, service_config in local.services :
    for container_name, container_config in service_config.containers :
    "${service_name}_${container_name}" => "/ecs/${local.environment}/${service_name}/image-tag"
  }
  
  name = each.value
}

# Updated service definitions with dynamic image tags
locals {
  services = {
    emojivoto = {
      cpu    = 2048
      memory = 8192

      containers = {
        web = {
          image   = "docker.l5d.io/buoyantio/emojivoto-web"
          version = data.aws_ssm_parameter.image_tags["emojivoto_web"].value  # ✅ Dynamic!
          
          cpu    = 512
          memory = 2048
          # ... rest of config
        }
        # ... other containers
      }
    }
  }
}

# Blue-Green Deployment Configuration
module "apps_devstg_ecs_cluster" {
  source = "github.com/binbashar/terraform-aws-ecs.git?ref=v5.12.1"

  # ... existing config ...

  services = { for service_name, service_values in local.services :
    service_name => {
      # ... existing config ...
      
      # Enable blue-green deployment
      deployment_controller = {
        type = "CODE_DEPLOY"  # Enables blue-green deployments
      }
      
      # ... rest of config ...
    }
  }
}
```

---

## 🛠️ Implementation Roadmap

*This phased approach minimizes risk by implementing changes incrementally, allowing teams to validate each stage before proceeding. The roadmap prioritizes foundational changes first, then builds automation capabilities, and finally adds advanced features like blue-green deployments.*

### Phase 1: Repository Setup & Parameterization
**Duration**: 1-2 weeks
- [ ] Add Parameter Store data sources to [`locals.tf`](https://github.com/binbashar/le-tf-infra-aws/blob/master/apps-devstg/us-east-1/ecs-demoapps/locals.tf)
- [ ] Create Parameter Store parameters for image tags
- [ ] Set up repository variables in application repository
- [ ] Test parameter-based image references

### Phase 2: Application Repository Workflow  
**Duration**: 1-2 weeks
- [ ] Create GitHub Actions workflow for application repository
- [ ] Set up AWS OIDC authentication
- [ ] Implement ECR push and parameter store updates
- [ ] Test repository dispatch integration

### Phase 3: Infrastructure Repository Workflow
**Duration**: 2-3 weeks
- [ ] Create GitHub Actions workflow for infrastructure repository
- [ ] Set up Leverage CLI in GitHub Actions runner
- [ ] Implement plan validation logic
- [ ] Add automated apply with safety checks

### Phase 4: Blue-Green Configuration
**Duration**: 1 week  
- [ ] Add blue-green deployment configuration to ECS module
- [ ] Configure additional target groups for blue-green
- [ ] Test blue-green deployment end-to-end

### Phase 5: Monitoring & Rollback
**Duration**: 1-2 weeks
- [ ] Add deployment status notifications
- [ ] Implement automated rollback on failure
- [ ] Add monitoring and alerting integration
- [ ] Create deployment dashboards

---

## 🔗 Technical References

### AWS Documentation
- [ECS Blue/Green Deployments](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-blue-green.html)
- [ECS Blue/Green Implementation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/blue-green-deployment-implementation.html)
- [AWS Blog: Built-in Blue/Green Deployments](https://aws.amazon.com/blogs/aws/accelerate-safe-software-releases-with-new-built-in-blue-green-deployments-in-amazon-ecs/)

### Current Implementation Code References
- **ECS Module**: [`terraform-aws-ecs/modules/service/main.tf:81`](https://github.com/binbashar/terraform-aws-ecs/blob/master/modules/service/main.tf#L81) - Blue-green deployment support
- **Current ECS Config**: [`apps-devstg/us-east-1/ecs-demoapps/ecs.tf:24`](https://github.com/binbashar/le-tf-infra-aws/blob/master/apps-devstg/us-east-1/ecs-demoapps/ecs.tf#L24) - Cluster definition
- **Service Definitions**: [`apps-devstg/us-east-1/ecs-demoapps/locals.tf:7`](https://github.com/binbashar/le-tf-infra-aws/blob/master/apps-devstg/us-east-1/ecs-demoapps/locals.tf#L7) - Container configurations  
- **ALB Configuration**: [`apps-devstg/us-east-1/ecs-demoapps/alb.tf:47`](https://github.com/binbashar/le-tf-infra-aws/blob/master/apps-devstg/us-east-1/ecs-demoapps/alb.tf#L47) - Load balancer setup

---

## ✅ Key Benefits of Refined Solution

*These benefits translate directly to improved developer productivity, reduced operational overhead, and enhanced system reliability. The solution addresses common pain points in enterprise container deployments while maintaining the security and compliance standards required for production systems.*

### Full GitOps Automation
- ✅ **Zero Human Intervention**: Merge PR → Fully automated deployment
- ✅ **Repository Separation**: Clean separation between app and infrastructure concerns
- ✅ **Full Parameterization**: No hardcoded values, completely configurable

### Leverage CLI Integration  
- ✅ **Leverage CLI Exclusive**: All infrastructure operations through Leverage CLI
- ✅ **GitHub Actions Ready**: Proper setup in GitHub Actions runners
- ✅ **Consistent Tooling**: Maintains Leverage environment and patterns

### Safety & Validation
- ✅ **Automated Plan Validation**: Only expected ECS changes allowed
- ✅ **Parameter Synchronization**: Validates parameter store updates
- ✅ **Blue-Green Ready**: Built-in deployment strategy via Binbash ECS module

---

## 🎯 Success Criteria

*Success will be measured through both technical metrics (deployment frequency, lead time, recovery time) and operational outcomes (reduced manual interventions, improved developer experience, decreased infrastructure-related incidents). These criteria ensure the solution delivers tangible business value.*

- [ ] **Complete separation** of infrastructure and application deployments
- [ ] **Zero-downtime** blue-green deployments working via Binbash ECS module
- [ ] **Fully automated** GitOps pipeline with repository dispatch
- [ ] **Leverage CLI exclusive** usage for all infrastructure operations
- [ ] **Parameter-based** dynamic container image management  
- [ ] **Automated validation** with plan safety checks
- [ ] **Cross-repository** coordination without manual intervention

---

## 🏷️ Tags

#ECS #GitOps #BlueGreen #CICD #Infrastructure #Terraform #AWS #Leverage #ParameterStore #GitHub-Actions

---

**Created**: 2025-09-09  
**Updated**: 2025-09-09 (Refined Solution)  
**Issues**: [#580](https://github.com/binbashar/le-tf-infra-aws/issues/580), [#933](https://github.com/binbashar/le-tf-infra-aws/issues/933)  
**Status**: Refined Architecture Complete ✅

**Comment by exequielrafaela** [comment]
@hecberco @lgallard as discussed with @diego-ojeda-binbash we'll be implementing the blue/green feature in our ECS Stack, but postponing the GitOps approach for the future if a project explicitly requests it.

CC: @angelofenoglio @martingaleano @rodriguez-matias @juanmatias
